version: '3.3'

services:
  app:
    image: ghisiluizgustavo/demo-arch
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    ports:
      - '27017:27017'
    command: ["mongod", "--bind_ip_all"]
